### ISSUE TITLE
Nothing happened.

### ISSUE THREAD

**Issue by LeoneHaxor** [NekiCat/fim-better-document-importer#17]
I went through the requisite steps to download and install the userscript. 
>Downloaded the Chrome extension for Tampermonkey
>Downloaded and installed the script through Tampermonkey
>Made the As-is Adjustments on the settings page and hit Save Settings
>Went to my chapter and hit Import GDocs
>The GUI shown in the images popped up
>Selected my document
>Confirm button
>No text appeared in the editor.
>Attempted to select another document
>Odd formatting in it makes it believe that it has multiple chapters, and asks me to choose one to import
>Chooses one
>Same result as earlier

[I am using Windows XP, if that makes any difference.]

**Comment by NekiCat** [comment]
So no text is inserted into the editor. Which version of Chrome do you use? When you open the browser console (with Ctrl+Shift+J), could you tell me what errors there are?

It could be that your browser is not up to date. I've used some newer features that might not be available on older browsers. I'm planning on raising compatibility with older browsers, but haven't got to that yet. I'll better make a ticket for that as well.

Using Windows XP is not a problem btw., as long as your browser is up to date (but I suggest upgrading anyway, XP doesn't receive security updates anymore ;) )

**Comment by NekiCat** [comment]
I'm going to assume that you solved your problem, so I'm closing the issue. Feel free to comment on/reopen this issue if you have further questions.
