### ISSUE TITLE
Imported Documents don't actually seem to import.

### ISSUE THREAD

**Issue by Skijarama** [NekiCat/fim-better-document-importer#19]
So, using this awesome plugin I have been uploading chapters of my story to Fimfiction.net pretty easily. However, I have run into an issue where I try to import a document and the 'import document' icon does it's thing for a second and then just stops. No text appears in the chapter page and it remaisn just as blank,

I dunno why... but on a side note, I am experiencing issues with installing it each time I go to do that. The install button on the download page tells me that there were too many requests and to try again some other time. =/

**Comment by NekiCat** [comment]
Can you tell me what browser and which version of the browser you use? Also, it'd help very much if you can post the console output to see if there are any errors. You can open the browser console with Ctrl+Shift+J. (Some errors may be expected, others not so much).

I'm guessing you are installing the script via OpenUserJS? They unfortunately have some very strict throttling in place, nothing I can do about. You might be able to install the script from GitHub directly to circumvent that.

You probably don't need to reinstall the script, as well, if you want to update it. At least Tampermonkey has a function in its UI to update scripts in-place. This should also circumvent OpenUserJS.

**Comment by whatmustido** [comment]
I'm getting the same error in the latest version of chrome and I can't even open it in firefox. When I click 'Import GDoc' in firefox, this is the console output: https://i.gyazo.com/3649a6aece4e24db2371adda34bc27b5.png

When I click 'Import GDoc' in chrome and select the document, this is the browser output: https://i.gyazo.com/01036576a7b842099a1a499217e8ec26.png

**Comment by NekiCat** [comment]
Thank you very much for the images, and sorry for the bugs. These even seem to be two unrelated bugs at work.
* In Firefox, gapi is not defined - this indicates a problem with loading the Google API.
* In Chrome, the imported heading is not recognized - maybe the object got replaced along the way.

I'll take a look, hopefully I'll find the bugs soon.

**Comment by whatmustido** [comment]
I wouldn't worry too much about the firefox one. Something's been fucky with firefox for ages and I can't get other semi-common programs to open on it. I've resorted to using Chrome for anything that requires opening a window or dialogue box because I'm too lazy to reset firefox again.

**Comment by NekiCat** [comment]
I know what you mean. My own Firefox is getting quite slow, I should make a new profile, but I'm lazy as well...

Anyway, I've tested it with Firefox on my end and getting the same error like in Chrome when I'm importing the whole document, but not when I'm only importing a chapter. I guess your Firefox installation is not okay, but the other one is definitely a bug.

I can't do it right now, but I'll be home in a few hours and fix it then.

**Comment by whatmustido** [comment]
I highly doubt this will help you, but this is the document I'm trying to import: https://docs.google.com/document/d/1CBfpTz_gmYDN4IrlbH7hCKpEA626tmrONNhMA9_ASiw/edit

I was thinking it might have been the size, but I kinda doubt it.

**Comment by NekiCat** [comment]
I don't _think_ size is a problem. Most of the parsing is done by the browser itself, so it's not that much different in size than the document in an inline frame.

You might be able to mark your chapter caption as a heading (and add a second heading at the beginning or end) for a quick workaround, since importing a single chapter instead of the whole document works, but I guess this only matters if you are really pressed for time.

![Marking a heading](https://raw.githubusercontent.com/wiki/NekiCat/fim-better-document-importer/images/installation/gdocs-heading.png)
