### ISSUE TITLE
Chrome can't use this userscript

### ISSUE THREAD

**Issue by NekiCat** [NekiCat/fim-better-document-importer#4]
Some users have reported that Chrome shows a bar saying that it cannot use the userscript.

More info is needed, like the exact words Chrome shows, the Browser version, OS, installed addons, maybe other?

**Comment by nicholasknight** [comment]
I went through the install process and took a recording, just to see if I could shed any light on what was going on. (I don't do any writing so can't actually put the importer to much practical use.)

The only thing I can think of is that the user(s) somehow aren't getting TamperMonkey correctly installed, or it's getting disabled. Conceivably some sort of permissions issue or rogue antivirus/"security" software?

On Chrome 55.0.2883.95, running on OS X 10.12.3, without TamperMonkey installed, I got the normal, expected, "Apps, extensions, and user scripts cannot be added from this website." bar.

With TamperMonkey installed, it seemed to work fine.

(This was tested by accessing the file directly on github, OpenUserJS has some crazy-strict rate limiting that makes practical testing almost impossible.)

Screencap attached. You can laugh at me as I struggle at the end with [TamperMonkey's current Mac UI bug](https://forum.tampermonkey.net/viewtopic.php?f=17&t=1939#p5946).

![tamper](https://cloud.githubusercontent.com/assets/973381/22627974/9f718a74-eb80-11e6-8d44-6a751d3ccdc4.gif)

**Comment by NekiCat** [comment]
Many thanks for the comment, especially your screencap! That helps very much.

I think this is an issue with a not-installed or not-enabled Tampermonkey, as well. I'm writing up an installation/how-to page in the wiki, that should hopefully help. (See also #8.)

I'll close this once I'm done with the tutorial.
