### ISSUE TITLE
Odd tags appearing

### ISSUE THREAD

**Issue by Krickis** [NekiCat/fim-better-document-importer#9]
I figured out what was going on with that issue I mentioned the other day with the random [a][b] tags appearing in my chapter upon import. They appear wherever there is an unresolved comment in the Gdoc. Interestingly, these go through the alphabet in sequence. So wherever the first comment is in the Gdoc will have the [a][b] appearing in the chapter text, while the second comment will have [c][d] tags and the third will have [e][f], so on and so forth.

**Comment by NekiCat** [comment]
Thanks for the report! This is definitely not something the Importer adds, so I guess Google adds these tags automatically. I will have a look at it and try to write a filter that removes these unresolved comments.

**Comment by Krickis** [comment]
This probably isn't at all helpful knowledge to you, but just in case it is, the original Fimfiction document importer does bring over comments. The default importer adds all the text from any comments to the bottom of the chapter rather than converting the comments into tags. If I recall correctly (and I might not), the import feature didn't originally bring over comments, and only started doing that around the time I first noticed bugs appearing in the import Gdoc feature. So I suppose it does seem likely that it's something on Google's end, since that didn't seem like an intended feature of Fimfiction's doc importer either.
